### ISSUE TITLE
Use ws instead of WebSocket if ws is available and opts is not empty

### ISSUE THREAD

**Issue by romaincointepas** [feross/simple-websocket#12]
Right now, when using simple-websocket in an electron renderer process and passing options (like an agent), simple-websocket will still use the browser WebSocket instead of ws, and will ignore the options.

It would make sense to force ws in that case: if opts are being passed, not using them is probably worse than using ws over WebSocket.

Note: without this fix (or a way to force ws over WebSocket), we can't use proxy in webtorrent for websocket trackers in an electron/renderer environment.

**Comment by feross** [comment]
Released as 4.2.0
