### ISSUE TITLE
Feature request: Reconnect if connection fails

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/simple-websocket#19]
It would be great if there was a way to detect if connection dies and try to reconnect.

Just like WebTorrent trackers ws do

**Comment by feross** [comment]
This used to be part of this package, but it was removed in 2.0.0. Here is the commit: https://github.com/feross/simple-websocket/commit/4b6d5d044910d019d0a72935f8f2d621f7758813

IMO, this functionality doesn't belong inside this package. It's simple enough to add outside.
