### ISSUE TITLE
Sometimes will get an error "Cannot read property 'send' of null"

### ISSUE THREAD

**Issue by XieShangxu** [feross/simple-websocket#23]
Sometimes will get an error "Cannot read property 'send' of null".

The root cause is the following code:
```
Socket.prototype.send = function (chunk) {
  this._ws.send(chunk)
}
```

I'am asking if you can kindly add an empty check before call the send function?
My suggestion code is that:
```
Socket.prototype.send = function (chunk) {
  this._ws && this._ws.send(chunk)
}
```

**Comment by feross** [comment]
Thanks for opening this issue. I think that this is an issue in your own code. There are only two places where `socket.send()` is called internally and they both check `socket.destroyed` first so it seems there is no way for this error to happen unless your code is calling `socket.send()` on a destroyed socket.

If you can provide an example of code that reproduces this, I'm happy to take a look at it.

**Comment by vdoddichintala** [comment]
Hi @feross ,
I am also facing the same issue.
Can you please help me
