### ISSUE TITLE
Bug with electron

### ISSUE THREAD

**Issue by artonge** [feross/simple-websocket#5]
When used in electron I have to comment line 10 of index.js `var ws = require('ws')` for the module to work.

I don't now why.

I've come across that bug when playing with torrent-stream.

**Comment by feross** [comment]
Have you changed your version of node recently? Try deleting your `node_modules` folder and running `npm install` again with the new version.

**Comment by artonge** [comment]
Just did and no results.

I don't know what the 'ws' module is, but it seems to me that it's not found.

**Comment by artonge** [comment]
Apparently electron is using io.js v3.1.0.Could this be the problem ?

**Comment by feross** [comment]
The `ws` no longer uses any native dependencies, so this issue is almost certainly gone. Closing.
