### ISSUE TITLE
Unspecified JSON.parse

### ISSUE THREAD

**Issue by polkovnikov-ph** [feross/simple-websocket#6]
It's not specified in the manual that the string that gets passed to `data` event listener gets decoded if it looks like JSON. This behaviour is implicit and the worst thing is that it works on strings that look like JSON but are not JSON. It was a really bad idea to toss

    try {
      data = JSON.parse(data)
    } catch (err) {}

into the source.

**Comment by feross** [comment]
Thanks for the issue! I think you might be right.

Has this been an issue for you in real production code? Or is this primarily a theoretical objection?

**Comment by polkovnikov-ph** [comment]
@feross Yep, that's from production.

**Comment by feross** [comment]
Updated the documentation so this behavior is clearer.

**Comment by polkovnikov-ph** [comment]
Um, sorry, that was not a question, but a bug. This is not a kind of behaviour that should be documented, but burned with fire. It spontaneously parses text as if it was JSON on some strings in production. If somebody was up to use this library in such cases, he'd have to escape strings (e.g. by adding and removing `a` char in the front of the string) to counteract this behaviour.

**Comment by feross** [comment]
I don't appreciate the snark. You're not paying for `simple-websocket`, so please don't act so entitled.

That said, I happen to agree with you. The documentation update was better than nothing, but the behavior should be removed. That is now done in https://github.com/feross/simple-websocket/commit/803716d3b2499d45f6144709a5e5527ea13a7b64 and 4.0.0.

**Comment by polkovnikov-ph** [comment]
@feross I've just got tired by the fact that out of a hundred reported bugs there're no more than five that get really fixed. Sorry, was in a bad mood that evening :/

**Comment by feross** [comment]
No problem :) Software is so hard. So many issues, so little time. Thanks again for the report.
